locations = {'US': ['auburn', 'bham', 'dothan', 'shoals', 'gadsden', 'huntsville', 'mobile', 'montgomery', 'tuscaloosa',
                    'anchorage', 'fairbanks', 'kenai', 'juneau', 'flagstaff', 'mohave', 'phoenix', 'prescott',
                    'showlow', 'sierravista', 'tucson', 'yuma', 'fayar', 'fortsmith', 'jonesboro', 'littlerock',
                    'texarkana', 'bakersfield', 'chico', 'fresno', 'goldcountry', 'hanford', 'humboldt', 'imperial',
                    'inlandempire', 'losangeles', 'mendocino', 'merced', 'modesto', 'monterey', 'orangecounty',
                    'palmsprings', 'redding', 'sacramento', 'sandiego', 'sfbay', 'slo', 'santabarbara', 'santamaria',
                    'siskiyou', 'stockton', 'susanville', 'ventura', 'visalia', 'yubasutter', 'boulder', 'cosprings',
                    'denver', 'eastco', 'fortcollins', 'rockies', 'pueblo', 'westslope', 'newlondon', 'hartford',
                    'newhaven', 'nwct', 'delaware', 'washingtondc', 'miami', 'daytona', 'keys', 'fortlauderdale',
                    'fortmyers', 'gainesville', 'cfl', 'jacksonville', 'lakeland', 'miami', 'lakecity', 'ocala',
                    'okaloosa', 'orlando', 'panamacity', 'pensacola', 'sarasota', 'miami', 'spacecoast', 'staugustine',
                    'tallahassee', 'tampa', 'treasure', 'miami', 'albanyga', 'athensga', 'atlanta', 'augusta',
                    'brunswick', 'columbusga', 'macon', 'nwga', 'savannah', 'statesboro', 'valdosta', 'honolulu',
                    'boise', 'eastidaho', 'lewiston', 'twinfalls', 'bn', 'chambana', 'chicago', 'decatur', 'lasalle',
                    'mattoon', 'peoria', 'rockford', 'carbondale', 'springfieldil', 'quincy', 'bloomington',
                    'evansville', 'fortwayne', 'indianapolis', 'kokomo', 'tippecanoe', 'muncie', 'richmondin',
                    'southbend', 'terrehaute', 'ames', 'cedarrapids', 'desmoines', 'dubuque', 'fortdodge', 'iowacity',
                    'masoncity', 'quadcities', 'siouxcity', 'ottumwa', 'waterloo', 'lawrence', 'ksu', 'nwks', 'salina',
                    'seks', 'swks', 'topeka', 'wichita', 'bgky', 'eastky', 'lexington', 'louisville', 'owensboro',
                    'westky', 'batonrouge', 'cenla', 'houma', 'lafayette', 'lakecharles', 'monroe', 'neworleans',
                    'shreveport', 'maine', 'annapolis', 'baltimore', 'easternshore', 'frederick', 'smd', 'westmd',
                    'boston', 'capecod', 'southcoast', 'westernmass', 'worcester', 'annarbor', 'battlecreek',
                    'centralmich', 'detroit', 'flint', 'grandrapids', 'holland', 'jxn', 'kalamazoo', 'lansing',
                    'monroemi', 'muskegon', 'nmi', 'porthuron', 'saginaw', 'swmi', 'thumb', 'up', 'bemidji', 'brainerd',
                    'duluth', 'mankato', 'minneapolis', 'rmn', 'marshall', 'stcloud', 'gulfport', 'hattiesburg',
                    'jackson', 'meridian', 'northmiss', 'natchez', 'columbiamo', 'joplin', 'kansascity', 'kirksville',
                    'loz', 'semo', 'springfield', 'stjoseph', 'stlouis', 'billings', 'bozeman', 'butte', 'greatfalls',
                    'helena', 'kalispell', 'missoula', 'montana', 'grandisland', 'lincoln', 'northplatte', 'omaha',
                    'scottsbluff', 'elko', 'lasvegas', 'reno', 'nh', 'cnj', 'jerseyshore', 'newjersey', 'southjersey',
                    'albuquerque', 'clovis', 'farmington', 'lascruces', 'roswell', 'santafe', 'albany', 'binghamton',
                    'buffalo', 'catskills', 'chautauqua', 'elmira', 'fingerlakes', 'glensfalls', 'hudsonvalley',
                    'ithaca', 'longisland', 'newyork', 'oneonta', 'plattsburgh', 'potsdam', 'rochester', 'syracuse',
                    'twintiers', 'utica', 'watertown', 'asheville', 'boone', 'charlotte', 'eastnc', 'fayetteville',
                    'greensboro', 'hickory', 'onslow', 'outerbanks', 'raleigh', 'wilmington', 'winstonsalem',
                    'bismarck', 'fargo', 'grandforks', 'nd', 'akroncanton', 'ashtabula', 'athensohio', 'chillicothe',
                    'cincinnati', 'cleveland', 'columbus', 'dayton', 'limaohio', 'mansfield', 'sandusky', 'toledo',
                    'tuscarawas', 'youngstown', 'zanesville', 'lawton', 'enid', 'oklahomacity', 'stillwater', 'tulsa',
                    'bend', 'corvallis', 'eastoregon', 'eugene', 'klamath', 'medford', 'oregoncoast', 'portland',
                    'roseburg', 'salem', 'altoona', 'chambersburg', 'erie', 'harrisburg', 'lancaster', 'allentown',
                    'meadville', 'philadelphia', 'pittsburgh', 'poconos', 'reading', 'scranton', 'pennstate',
                    'williamsport', 'york', 'providence', 'charleston', 'columbia', 'florencesc', 'greenville',
                    'hiltonhead', 'myrtlebeach', 'nesd', 'csd', 'rapidcity', 'siouxfalls', 'sd', 'chattanooga',
                    'clarksville', 'cookeville', 'jacksontn', 'knoxville', 'memphis', 'nashville', 'tricities',
                    'abilene', 'amarillo', 'austin', 'beaumont', 'brownsville', 'collegestation', 'corpuschristi',
                    'dallas', 'nacogdoches', 'delrio', 'elpaso', 'galveston', 'houston', 'killeen', 'laredo', 'lubbock',
                    'mcallen', 'odessa', 'sanangelo', 'sanantonio', 'sanmarcos', 'bigbend', 'texoma', 'easttexas',
                    'victoriatx', 'waco', 'wichitafalls', 'logan', 'ogden', 'provo', 'saltlakecity', 'stgeorge',
                    'burlington', 'charlottesville', 'danville', 'fredericksburg', 'norfolk', 'harrisonburg',
                    'lynchburg', 'blacksburg', 'richmond', 'roanoke', 'swva', 'winchester', 'bellingham', 'kpr',
                    'moseslake', 'olympic', 'pullman', 'seattle', 'skagit', 'spokane', 'wenatchee', 'yakima',
                    'charlestonwv', 'martinsburg', 'huntington', 'morgantown', 'wheeling', 'parkersburg', 'swv', 'wv',
                    'appleton', 'eauclaire', 'greenbay', 'janesville', 'racine', 'lacrosse', 'madison', 'milwaukee',
                    'northernwi', 'sheboygan', 'wausau', 'wyoming', 'micronesia', 'puertorico', 'virgin']}

all_locations = {
    'Asia, Pacific and Middle East': ['bangladesh', 'beijing', 'chengdu', 'chongqing', 'dalian', 'guangzhou',
                                      'hangzhou', 'nanjing', 'shanghai', 'shenyang', 'shenzhen', 'wuhan',
                                      'xian', 'micronesia', 'hongkong', 'ahmedabad', 'bangalore',
                                      'bhubaneswar', 'chandigarh', 'chennai', 'delhi', 'goa', 'hyderabad',
                                      'indore', 'jaipur', 'kerala', 'kolkata', 'lucknow', 'mumbai', 'pune',
                                      'surat', 'jakarta', 'tehran', 'baghdad', 'haifa', 'jerusalem', 'telaviv',
                                      'ramallah', 'fukuoka', 'hiroshima', 'nagoya', 'okinawa', 'osaka',
                                      'sapporo', 'sendai', 'tokyo', 'seoul', 'kuwait', 'beirut', 'malaysia',
                                      'pakistan', 'bacolod', 'naga', 'cdo', 'cebu', 'davaocity', 'iloilo',
                                      'manila', 'pampanga', 'zamboanga', 'singapore', 'taipei', 'bangkok',
                                      'dubai', 'vietnam'],
    'Oceania': ['adelaide', 'brisbane', 'cairns', 'canberra', 'darwin', 'goldcoast', 'melbourne', 'ntl',
                'perth', 'sydney', 'hobart', 'wollongong', 'auckland', 'christchurch', 'dunedin',
                'wellington'],
    'Canada': ['calgary', 'edmonton', 'ftmcmurray', 'lethbridge', 'hat', 'peace', 'reddeer', 'cariboo',
               'comoxvalley', 'abbotsford', 'kamloops', 'kelowna', 'cranbrook', 'nanaimo', 'princegeorge',
               'skeena', 'sunshine', 'vancouver', 'victoria', 'whistler', 'winnipeg', 'newbrunswick',
               'newfoundland', 'territories', 'yellowknife', 'halifax', 'barrie', 'belleville', 'brantford',
               'chatham', 'cornwall', 'guelph', 'hamilton', 'kingston', 'kitchener', 'londonon', 'niagara',
               'ottawa', 'owensound', 'peterborough', 'sarnia', 'soo', 'sudbury', 'thunderbay', 'toronto',
               'windsor', 'pei', 'montreal', 'quebec', 'saguenay', 'sherbrooke', 'troisrivieres', 'regina',
               'saskatoon', 'whitehorse'],
    'US': ['auburn', 'bham', 'dothan', 'shoals', 'gadsden', 'huntsville', 'mobile', 'montgomery', 'tuscaloosa',
           'anchorage', 'fairbanks', 'kenai', 'juneau', 'flagstaff', 'mohave', 'phoenix', 'prescott',
           'showlow', 'sierravista', 'tucson', 'yuma', 'fayar', 'fortsmith', 'jonesboro', 'littlerock',
           'texarkana', 'bakersfield', 'chico', 'fresno', 'goldcountry', 'hanford', 'humboldt', 'imperial',
           'inlandempire', 'losangeles', 'mendocino', 'merced', 'modesto', 'monterey', 'orangecounty',
           'palmsprings', 'redding', 'sacramento', 'sandiego', 'sfbay', 'slo', 'santabarbara', 'santamaria',
           'siskiyou', 'stockton', 'susanville', 'ventura', 'visalia', 'yubasutter', 'boulder', 'cosprings',
           'denver', 'eastco', 'fortcollins', 'rockies', 'pueblo', 'westslope', 'newlondon', 'hartford',
           'newhaven', 'nwct', 'delaware', 'washingtondc', 'miami', 'daytona', 'keys', 'fortlauderdale',
           'fortmyers', 'gainesville', 'cfl', 'jacksonville', 'lakeland', 'miami', 'lakecity', 'ocala',
           'okaloosa', 'orlando', 'panamacity', 'pensacola', 'sarasota', 'miami', 'spacecoast', 'staugustine',
           'tallahassee', 'tampa', 'treasure', 'miami', 'albanyga', 'athensga', 'atlanta', 'augusta',
           'brunswick', 'columbusga', 'macon', 'nwga', 'savannah', 'statesboro', 'valdosta', 'honolulu',
           'boise', 'eastidaho', 'lewiston', 'twinfalls', 'bn', 'chambana', 'chicago', 'decatur', 'lasalle',
           'mattoon', 'peoria', 'rockford', 'carbondale', 'springfieldil', 'quincy', 'bloomington',
           'evansville', 'fortwayne', 'indianapolis', 'kokomo', 'tippecanoe', 'muncie', 'richmondin',
           'southbend', 'terrehaute', 'ames', 'cedarrapids', 'desmoines', 'dubuque', 'fortdodge', 'iowacity',
           'masoncity', 'quadcities', 'siouxcity', 'ottumwa', 'waterloo', 'lawrence', 'ksu', 'nwks', 'salina',
           'seks', 'swks', 'topeka', 'wichita', 'bgky', 'eastky', 'lexington', 'louisville', 'owensboro',
           'westky', 'batonrouge', 'cenla', 'houma', 'lafayette', 'lakecharles', 'monroe', 'neworleans',
           'shreveport', 'maine', 'annapolis', 'baltimore', 'easternshore', 'frederick', 'smd', 'westmd',
           'boston', 'capecod', 'southcoast', 'westernmass', 'worcester', 'annarbor', 'battlecreek',
           'centralmich', 'detroit', 'flint', 'grandrapids', 'holland', 'jxn', 'kalamazoo', 'lansing',
           'monroemi', 'muskegon', 'nmi', 'porthuron', 'saginaw', 'swmi', 'thumb', 'up', 'bemidji', 'brainerd',
           'duluth', 'mankato', 'minneapolis', 'rmn', 'marshall', 'stcloud', 'gulfport', 'hattiesburg',
           'jackson', 'meridian', 'northmiss', 'natchez', 'columbiamo', 'joplin', 'kansascity', 'kirksville',
           'loz', 'semo', 'springfield', 'stjoseph', 'stlouis', 'billings', 'bozeman', 'butte', 'greatfalls',
           'helena', 'kalispell', 'missoula', 'montana', 'grandisland', 'lincoln', 'northplatte', 'omaha',
           'scottsbluff', 'elko', 'lasvegas', 'reno', 'nh', 'cnj', 'jerseyshore', 'newjersey', 'southjersey',
           'albuquerque', 'clovis', 'farmington', 'lascruces', 'roswell', 'santafe', 'albany', 'binghamton',
           'buffalo', 'catskills', 'chautauqua', 'elmira', 'fingerlakes', 'glensfalls', 'hudsonvalley',
           'ithaca', 'longisland', 'newyork', 'oneonta', 'plattsburgh', 'potsdam', 'rochester', 'syracuse',
           'twintiers', 'utica', 'watertown', 'asheville', 'boone', 'charlotte', 'eastnc', 'fayetteville',
           'greensboro', 'hickory', 'onslow', 'outerbanks', 'raleigh', 'wilmington', 'winstonsalem',
           'bismarck', 'fargo', 'grandforks', 'nd', 'akroncanton', 'ashtabula', 'athensohio', 'chillicothe',
           'cincinnati', 'cleveland', 'columbus', 'dayton', 'limaohio', 'mansfield', 'sandusky', 'toledo',
           'tuscarawas', 'youngstown', 'zanesville', 'lawton', 'enid', 'oklahomacity', 'stillwater', 'tulsa',
           'bend', 'corvallis', 'eastoregon', 'eugene', 'klamath', 'medford', 'oregoncoast', 'portland',
           'roseburg', 'salem', 'altoona', 'chambersburg', 'erie', 'harrisburg', 'lancaster', 'allentown',
           'meadville', 'philadelphia', 'pittsburgh', 'poconos', 'reading', 'scranton', 'pennstate',
           'williamsport', 'york', 'providence', 'charleston', 'columbia', 'florencesc', 'greenville',
           'hiltonhead', 'myrtlebeach', 'nesd', 'csd', 'rapidcity', 'siouxfalls', 'sd', 'chattanooga',
           'clarksville', 'cookeville', 'jacksontn', 'knoxville', 'memphis', 'nashville', 'tricities',
           'abilene', 'amarillo', 'austin', 'beaumont', 'brownsville', 'collegestation', 'corpuschristi',
           'dallas', 'nacogdoches', 'delrio', 'elpaso', 'galveston', 'houston', 'killeen', 'laredo', 'lubbock',
           'mcallen', 'odessa', 'sanangelo', 'sanantonio', 'sanmarcos', 'bigbend', 'texoma', 'easttexas',
           'victoriatx', 'waco', 'wichitafalls', 'logan', 'ogden', 'provo', 'saltlakecity', 'stgeorge',
           'burlington', 'charlottesville', 'danville', 'fredericksburg', 'norfolk', 'harrisonburg',
           'lynchburg', 'blacksburg', 'richmond', 'roanoke', 'swva', 'winchester', 'bellingham', 'kpr',
           'moseslake', 'olympic', 'pullman', 'seattle', 'skagit', 'spokane', 'wenatchee', 'yakima',
           'charlestonwv', 'martinsburg', 'huntington', 'morgantown', 'wheeling', 'parkersburg', 'swv', 'wv',
           'appleton', 'eauclaire', 'greenbay', 'janesville', 'racine', 'lacrosse', 'madison', 'milwaukee',
           'northernwi', 'sheboygan', 'wausau', 'wyoming', 'micronesia', 'puertorico', 'virgin'],
    'Africa': ['cairo', 'addisababa', 'accra', 'kenya', 'casablanca', 'capetown', 'durban', 'johannesburg',
               'pretoria', 'tunis'],
    'Europe': ['vienna', 'brussels', 'bulgaria', 'zagreb', 'prague', 'copenhagen', 'helsinki', 'bordeaux',
               'rennes', 'grenoble', 'lille', 'loire', 'lyon', 'marseilles', 'montpellier', 'cotedazur',
               'rouen', 'paris', 'strasbourg', 'toulouse', 'berlin', 'bremen', 'cologne', 'dresden',
               'dusseldorf', 'essen', 'frankfurt', 'hamburg', 'hannover', 'heidelberg', 'kaiserslautern',
               'leipzig', 'munich', 'nuremberg', 'stuttgart', 'athens', 'budapest', 'reykjavik', 'dublin',
               'bologna', 'florence', 'genoa', 'milan', 'naples', 'perugia', 'rome', 'sardinia', 'sicily',
               'torino', 'venice', 'luxembourg', 'amsterdam', 'oslo', 'warsaw', 'faro', 'lisbon', 'porto',
               'bucharest', 'moscow', 'stpetersburg', 'alicante', 'baleares', 'barcelona', 'bilbao', 'cadiz',
               'canarias', 'granada', 'madrid', 'malaga', 'sevilla', 'valencia', 'stockholm', 'basel', 'bern',
               'geneva', 'lausanne', 'zurich', 'istanbul', 'ukraine', 'aberdeen', 'bath', 'belfast',
               'birmingham', 'brighton', 'bristol', 'cambridge', 'cardiff', 'coventry', 'derby', 'devon',
               'dundee', 'norwich', 'eastmids', 'edinburgh', 'essex', 'glasgow', 'hampshire', 'kent', 'leeds',
               'liverpool', 'london', 'manchester', 'newcastle', 'nottingham', 'oxford', 'sheffield'],
    'Latin America and Caribbean': ['buenosaires', 'lapaz', 'belohorizonte', 'brasilia', 'curitiba',
                                    'fortaleza', 'portoalegre', 'recife', 'rio', 'salvador', 'saopaulo',
                                    'caribbean', 'santiago', 'colombia', 'costarica', 'santodomingo', 'quito',
                                    'elsalvador', 'guatemala', 'acapulco', 'bajasur', 'chihuahua', 'juarez',
                                    'guadalajara', 'guanajuato', 'hermosillo', 'mazatlan', 'mexicocity',
                                    'monterrey', 'oaxaca', 'puebla', 'pv', 'tijuana', 'veracruz', 'yucatan',
                                    'managua', 'panama', 'lima', 'puertorico', 'montevideo', 'caracas',
                                    'virgin']
}
